# Generated by Django 3.1.1 on 2020-09-10 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('reason', models.CharField(choices=[('CH', 'Annual Checkup'), ('GC', 'General Consultation'), ('GF', 'General Follow Up'), ('NP', 'New Patient Visit'), ('SD', 'Screening for Disease'), ('VC', 'Vaccination')], default='GC', max_length=2)),
                ('new_patient', models.BooleanField()),
                ('contact_phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone numbers must be in the format (xxx)xxx-xxxx', regex='\\([1-9][\\d]{2}\\)[1-9][\\d]{2}-[1-9][\\d]{3}')])),
            ],
        ),
    ]
